### PR TITLE
Bookstore setup

### PR DESCRIPTION
**Pull request by inspecta**
- Create a new repository
- Use Gitflow to create branches
- Initialise React app in a feature branch
- Create reusable components as building blocks of the app
- Added [React Router] and set two <Route>s and <Link>s for the app's navigation:
- Book to display along with remove button
- Created a component called Book for displaying a single book (receive a title and an author as a prop) 
- Display a form for adding a book
- Create a separate component for this form
- Categories display a button "Check status" only.

### CODE REVIEW

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi @inspecta, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
- No linter errors
- correct flow is used
- good PR

## Required Changes ♻️

- [ ] Good job so far 👏 I  can't be able to add a new book.  Please add a component to render book data 😃 
- [ ] Make sure that a new book rendered has `remove` button so that the user can be able to remove it 😃 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by inspecta** [comment]
@BertrandConxy, thanks for the feedback. I hadn't added the functionality because it was out of the requirements scope. But I'll implement it.

**Comment by BertrandConxy** [comment]
@inspecta yeah I think It would be better😎

**Review by mahbubul14 — APPROVED** [review]
# Project Approved :trophy: :tada: 

Hi @inspecta, 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive PR.
:heavy_check_mark: Well-implemented requirements.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by inspecta** [comment]
Thanks @mahbubul14

**Pull request merged**
